spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/image'
    username: postgres
    password: JaS1M$otGr0W
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop

expected:
  password: 123

jwt:
  password: 123
  subject: 'User details'
  issuer: 'Gaziyev'